// ==================== 악기 데이터 ====================
export const INSTRUMENTS_DATA = {
  // 현악기
  violin: {
    id: "violin",
    name: "바이올린",
    group: "strings",
    groupName: "현악기",
    emoji: "🎻",
    color: "#FF6B6B",
    soundId: 575619,
    description:
      "오케스트라에서 가장 높은 음역을 담당하며, 주로 주선율을 연주합니다.",
    position: { x: 45, y: 30 },
  },
  viola: {
    id: "viola",
    name: "비올라",
    group: "strings",
    groupName: "현악기",
    emoji: "🎻",
    color: "#FFA07A",
    soundId: 621846,
    description: "바이올린보다 낮은 음역으로 중음부를 담당합니다.",
    position: { x: 70, y: 50 },
  },
  cello: {
    id: "cello",
    name: "첼로",
    group: "strings",
    groupName: "현악기",
    emoji: "🎻",
    color: "#CD853F",
    soundId: 124001,
    description: "따뜻하고 깊은 저음을 담당하는 현악기입니다.",
    position: { x: 20, y: 50 },
  },
  doublebass: {
    id: "doublebass",
    name: "더블베이스",
    group: "strings",
    groupName: "현악기",
    emoji: "🎻",
    color: "#8B4513",
    soundId: 613397,
    description: "현악기 중 가장 낮고 깊은 저음을 담당합니다.",
    position: { x: 10, y: 65 },
  },
  // 목관악기
  flute: {
    id: "flute",
    name: "플루트",
    group: "woodwinds",
    groupName: "목관악기",
    emoji: "🎺",
    color: "#4ECDC4",
    soundFile: "/music/flute.mp3",
    description: "맑고 청아한 고음을 내는 목관악기입니다.",
    position: { x: 35, y: 60 },
  },
  oboe: {
    id: "oboe",
    name: "오보에",
    group: "woodwinds",
    groupName: "목관악기",
    emoji: "🎺",
    color: "#45B7D1",
    soundId: 350426,
    description: "날카롭고 독특한 음색을 가진 더블리드 악기입니다.",
    position: { x: 45, y: 60 },
  },
  clarinet: {
    id: "clarinet",
    name: "클라리넷",
    group: "woodwinds",
    groupName: "목관악기",
    emoji: "🎺",
    color: "#5F9EA0",
    soundFile: "/music/clarinet.mp3",
    description: "넓은 음역과 부드러운 음색을 가진 싱글리드 악기입니다.",
    position: { x: 55, y: 60 },
  },
  bassoon: {
    id: "bassoon",
    name: "바순",
    group: "woodwinds",
    groupName: "목관악기",
    emoji: "🎺",
    color: "#4682B4",
    soundId: 450527,
    description: "목관악기 중 가장 낮은 음역을 담당합니다.",
    position: { x: 65, y: 60 },
  },
  // 금관악기
  horn: {
    id: "horn",
    name: "호른",
    group: "brass",
    groupName: "금관악기",
    emoji: "📯",
    color: "#FFD93D",
    soundId: 362203,
    description: "부드럽고 풍부한 음색의 금관악기입니다.",
    position: { x: 30, y: 75 },
  },
  trumpet: {
    id: "trumpet",
    name: "트럼펫",
    group: "brass",
    groupName: "금관악기",
    emoji: "🎺",
    color: "#FFC312",
    soundId: 329349,
    description: "밝고 화려한 고음을 내는 금관악기입니다.",
    position: { x: 45, y: 75 },
  },
  trombone: {
    id: "trombone",
    name: "트롬본",
    group: "brass",
    groupName: "금관악기",
    emoji: "🎺",
    color: "#F79F1F",
    soundId: 73750,
    description: "슬라이드로 음높이를 조절하는 금관악기입니다.",
    position: { x: 60, y: 75 },
  },
  tuba: {
    id: "tuba",
    name: "튜바",
    group: "brass",
    groupName: "금관악기",
    emoji: "🎺",
    color: "#EE5A6F",
    soundFile: "/music/tuba.mp3",
    description: "금관악기 중 가장 낮은 저음을 담당합니다.",
    position: { x: 75, y: 75 },
  },
  // 타악기
  timpani: {
    id: "timpani",
    name: "팀파니",
    group: "percussion",
    groupName: "타악기",
    emoji: "🥁",
    color: "#8B4513",
    soundId: 668439,
    description:
      "오케스트라에서 사용되는 큰 북으로 음높이를 조절할 수 있습니다.",
    position: { x: 40, y: 88 },
  },
  snare: {
    id: "snare",
    name: "스네어 드럼",
    group: "percussion",
    groupName: "타악기",
    emoji: "🥁",
    color: "#A0522D",
    soundId: 663323,
    description: "날카롭고 경쾌한 소리를 내는 작은 북입니다.",
    position: { x: 50, y: 88 },
  },
  cymbals: {
    id: "cymbals",
    name: "심벌즈",
    group: "percussion",
    groupName: "타악기",
    emoji: "🎵",
    color: "#DAA520",
    soundId: 138362,
    description: "금속제 타악기로 강렬한 음색을 냅니다.",
    position: { x: 60, y: 88 },
  },
  marimba: {
    id: "marimba",
    name: "마림바",
    group: "percussion",
    groupName: "타악기",
    emoji: "🎹",
    color: "#CD853F",
    soundFile: "/music/marimba.mp3",
    description: "나무 건반을 두드려 연주하는 선율 타악기입니다.",
    position: { x: 70, y: 88 },
  },
};
